# -*- coding: utf-8 -*-
"""predict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vktB367VnWb_GS6lI-nDLA-rYjreYSC1
"""

#Se importan las librerías necesarias
import pandas as pd
import numpy as np
import joblib
from sklearn.preprocessing import LabelEncoder

#Se carga el modelo LGBM anteriormente entrenado
print("Charging model...")
model = joblib.load('model.pkl')

#Se cargan los datos para realizar las predicciones (solo variables predictoras)
print("Charging data for prediction...")
data = pd.read_csv('data.csv')

#Se convierten las columnas de fecha al formato datetime
data['Date_Registered'] = pd.to_datetime(data['Date_Registered'])
data['payment_datetime'] = pd.to_datetime(data['payment_datetime'])
data['purchased_datetime'] = pd.to_datetime(data['purchased_datetime'])
data['released_date'] = pd.to_datetime(data['released_date'])
data['estimated_delivery_date'] = pd.to_datetime(data['estimated_delivery_date'])
data['received_date'] = pd.to_datetime(data['received_date'])

#Se extraen las características temporales y se generan variables derivadas de las fechas (hora, día, mes, etc.)
data['purchase_hour'] = data['payment_datetime'].dt.hour
data['purchase_day'] = data['payment_datetime'].dt.day_name()
data['purchase_month'] = data['payment_datetime'].dt.month
data['days_since_registration'] = (data['purchased_datetime'] - data['Date_Registered']).dt.days
data['estimated_delivery_day'] = data['estimated_delivery_date'].dt.day_name()
data['received_day'] = data['received_date'].dt.day_name()

#Se convierten las columnas de fecha a timestamp de Unix
date_columns = ['Date_Registered', 'payment_datetime', 'purchased_datetime',
                'released_date', 'estimated_delivery_date', 'received_date']

for col in date_columns:
    data[col] = pd.to_datetime(data[col], errors='coerce').astype(int) / 10**9

#Se convierten las variables categóricas a un formato númerico
from sklearn.preprocessing import LabelEncoder

categorical_columns = ['Gender', 'Is_current_loyalty_program_member',
                       'product_category',
                       'payment_method', 'purchase_medium', 'shipping_method', 'purchase_day','estimated_delivery_day','received_day']

label_encoder = LabelEncoder()

for col in categorical_columns:
    data[col] = label_encoder.fit_transform(data[col].astype(str))

#Se crean nuevas variables derivadas de las fechas y variables económicas
data['Delivery_time'] = data['received_date'] - data['released_date']
data['Delivery_delay'] = data['received_date'] - data['estimated_delivery_date']
data['Waiting_time'] = data['received_date'] - data['payment_datetime']
data['Additional_charge'] = data['final_payment'] - data['Product_value']
data['Waiting_percentage'] = (data['received_date'] - data['estimated_delivery_date'])/(data['received_date'] - data['payment_datetime'])
data['Processing_time'] = data['released_date'] - data['payment_datetime']
data['Loyalty_engagement'] = data['loyalty_points_redeemed'] / data['Product_value']

#Convierte los valores no numéricos a valores nulos
data.replace(r'[^0-9]+', np.nan, regex=True, inplace=True)

#Cambia los valores faltantes por el número 0
data.fillna(0,inplace=True)

#Se convierte todo el Data Frame a tipo numérico
data = data.apply(pd.to_numeric)

#Se eliminan las variables que no son relevantes para la predicción
new_data=data.drop(['tracking_number', 'user_id', 'loyalty_tier','purchase_medium' ,'shipping_method','Gender','order_id', 'Received_tier_discount_percentage', 'Is_current_loyalty_program_member', 'transaction_id'], axis=1)

#Se realizan las predicciones con el modelo LGBM Classifier
print("Generating predictions...")
predictions = model.predict(new_data)

#Se convierten las predicciones numéricas del modelo en etiquetas textuales interpretables
#0: bad, 1: neutral, 2: good
mapping = {0: 'bad', 1: 'neutral', 2: 'good'}
predicted_labels = [mapping[prediction] for prediction in predictions]

#Se genera el archivo con las predicciones usando un dataframe con las columnas id y customer_experience (la estructura definida para el submission del Kaggle)
#Se exporta el dataframe en formato csv, en un archivo llamado predictions.csv
result = pd.DataFrame({'id': data['id'], 'customer_experience': predicted_labels})
result.to_csv('predictions.csv', index = False)
print("File predictions.csv generated succesfully.")